# Source language and JDK version to use
language: java
jdk: oraclejdk6

# Compile and package JAR and set build properties
install: true
script: gradle build -PbuildNumber=$TRAVIS_BUILD_NUMBER -PciSystem=travis -Pcommit=${TRAVIS_COMMIT:0:7}

# Perform steps after compilation/test success
after_success:
  # Check if commit s not a pull request, if git repo is official, and if branch is master. If checks pass, add libs and deploy artifacts to Maven repository.
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == ObsidianBox/Frames ]] && [[ $TRAVIS_BRANCH == master ]] && gradle uploadArchives"

# Notification services
notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false
  webhooks:
    # Send build information and status to Notifico
    - http://n.tkte.ch/h/3337/fF-aQGmZ_xo5Z0FB3HVZ46Sg

# Environmental system variables
env:
  global:
    # Make the log output cleaner
    - TERM=dumb
    # Super secure, encrypted variables! Ssssh!
    - secure: "Foo"
    - secure: "Bar"
